# Generated by Django 4.2.30 on 2026-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population_density', models.FloatField()),
                ('traffic_proxy', models.FloatField()),
                ('degree_centrality', models.FloatField()),
                ('betweenness_centrality', models.FloatField()),
                ('closeness_centrality', models.FloatField()),
                ('eigenvector_centrality', models.FloatField()),
                ('composite_importance', models.FloatField()),
                ('distance_to_nearest_existing_station', models.FloatField()),
                ('subregion_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-composite_importance'],
            },
        ),
        migrations.CreateModel(
            name='ExistingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('operator', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(default='synthetic_generated', max_length=64)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('objective_value', models.FloatField()),
                ('solver_status', models.CharField(max_length=32)),
                ('coverage_radius_m', models.FloatField()),
                ('before_pct_covered', models.FloatField()),
                ('after_pct_covered', models.FloatField()),
                ('before_avg_distance_m', models.FloatField(null=True)),
                ('after_avg_distance_m', models.FloatField(null=True)),
                ('selected_site_ids', models.JSONField(default=list)),
                ('solve_time_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(unique=True)),
                ('node_count', models.IntegerField()),
                ('centroid_lat', models.FloatField()),
                ('centroid_lon', models.FloatField()),
                ('total_demand', models.FloatField(default=0.0)),
                ('boundary', models.JSONField(default=list)),
            ],
        ),
    ]
